server:
  port: 80

# 名字
spring:
  application:
    name: provider-order-service
  zipkin:
    #zipkin的注册路径
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率值介于 0 到1 之间，1则表示全部采集
        probability: 1

eureka:
  client:
    ###是否将自己注册到注册中心  false 表示不想注册中心注册自己
    register-with-eureka: true
    ###是否从euerka中获取注册信息
    fetch-registry: true
    # 配置暴露给eureka client的请求路径
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka/ ,http://localhost:7002/eureka/  #集群版
      defaultZone: http://localhost:7001/eureka/  # 单机版