server:
  port: 7001  #端口号


spring:
  application:
    name: Eureka-Service7001   #服务名称


# 配置eureka server
eureka:
  instance:
    hostname: localhost   #主机地址名称
  client:
    ###是否将自己注册到注册中心  false 表示不想注册中心注册自己
    register-with-eureka: false
    ###是否从euerka中获取注册信息
    fetch-registry: false
    # 配置暴露给eureka client的请求路径
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/  #集群版
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
  server:
    enable-self-preservation: true     #自我保护机制，默认开启为true
    #eviction-interval-timer-in-ms: 2000 #接收心跳时间。默认90秒，单位为毫秒
