server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口

      datasource:
        ds1:    # 数据源 1
          nacos:
            server-addr: localhost:8848   # nacos  地址
            dataId: ${spring.application.name}  # 微服务名称
            groupId: DEFAULT_GROUP  #默认分组
            data-type: json   # json
            rule-type: flow

# 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'