server:
  port: 9527

spring:
  application:
    name: gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名创建路由
      routes: #路由
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://PROVIDER-PAYMENT-SERVICE  #使用微服务名
          predicates:
            - Path=/payment/find/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
        #uri: http://localhost:8001
          uri: lb://PROVIDER-PAYMENT-SERVICE
          predicates:
            - Path=/payment/port/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka